[package]
name = "joesmaller/enum-util"
description = "Library to create custom Enums"
version = "0.1.0"
license = "MIT"
authors = ["Joe Smaller <joe@gluon.games>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]

[dev-dependencies]